"""Second migration changed the name of blogpost in relationship with comments class

Revision ID: ec39f02f8bf4
Revises: b03c2f1be17e
Create Date: 2018-09-13 11:52:55.953852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec39f02f8bf4'
down_revision = 'b03c2f1be17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blogposts', sa.Integer(), nullable=True))
    op.drop_constraint('comments_blogpost_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'blogpost', ['blogposts'], ['id'])
    op.drop_column('comments', 'blogpost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blogpost', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_blogpost_fkey', 'comments', 'blogpost', ['blogpost'], ['id'])
    op.drop_column('comments', 'blogposts')
    # ### end Alembic commands ###
